easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\User
       - App\Entity\Formation
       - App\Entity\Situation
       - App\Entity\Categorie
       
